name: Movies
on:
  workflow_dispatch:
  schedule: 
    - cron: "0 1 * * *"
jobs:
  movies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "14"
    - run: cd movies && yarn
    - run: cd movies && node .
      env:
        PAT: ${{ secrets.MISC_PAT }}
        COMMITTER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
