name: Overall Metrics
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/overall-metrics.yml
  schedule: 
    - cron: "0 0 1 * *"
jobs:
  general-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Africa/Johannesburg
          config_padding: 5
          filename: overall-metrics.svg
          
          plugin_traffic: yes
          
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_categories: programming
          plugin_languages_ignored: tsx, css
          plugin_languages_aliases: RenderScript:Rust # temp solution until Rust as RenderScript bug is fixed
          commits_authoring: matievisthekat@gmail.com
          
          plugin_lines: yes
          
          plugin_followup: yes
          plugin_followup_sections: repositories, user
  language-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: no
          config_timezone: Africa/Johannesburg
          config_padding: 10, 10
          filename: overall-languages.svg
          extras_css: |
            svg, foreignObject, .items-wrapper {
              background-color: white;
            }
            
            div.row.footnote > .field {
              margin-right: 2%;
            }
          
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_details: percentage, lines, bytes-size
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_categories: programming
          plugin_languages_ignored: tsx, css
          plugin_languages_aliases: RenderScript:Rust # temp solution until Rust as RenderScript bug is fixed
          commits_authoring: matievisthekat@gmail.com
